### ISSUE TITLE
Array whitespace is changed between parse and stringify

### ISSUE THREAD

**Issue by pksunkara** [eemeli/yaml#570] opened 2024-08-23 14:05 UTC
**Describe the bug**
When I am parsing a YAML and stringifying it afterward, the whitespace in an array changes.

**To Reproduce**

Before:

```yml
on: [pull_request]
```

After:

```yml
on: [ pull_request ]
```

**Expected behaviour**

The after file should be the same as before

**Versions (please complete the following information):**

- `node`: 22
- `yaml`: 2.5.0

**Comment by eemeli** [comment] 2024-08-23 15:04
It's retained in the document that you get from `parseDocument`; the formatting is not retained in the JS representation.

**Comment by pksunkara** [comment] 2024-08-23 15:34
Oh, that makes sense. Let me see if I can use `parseDocument` and fix it.

**Comment by pksunkara** [comment] 2024-08-23 15:46
I haven't fully confirmed because I am still revamping my other logics, but it looks like the "After" version is adding spaces though.

```yml
on: [ pull_request ]
```

**Comment by pksunkara** [comment] 2024-09-02 01:14
Yup, I can confirm that the spaces choice between in the square brackets in array is not being preserved.

**Comment by eemeli** [comment] 2024-09-02 08:27
Normalising whitespace is done intentionally; information about it is not retained in the parsed document.

**Comment by pksunkara** [comment] 2024-09-02 11:33
In that case,

1. Do you plan to add support for it? (I might be willing to contribute here to this case.)
2. Is this the same cause for #572 too?

**Comment by eemeli** [comment] 2024-09-02 12:41
1. No; if you need to retain whitespace, you should be applying your changes to the CST and serialising that: https://eemeli.org/yaml/#working-with-cst-tokens
2. Same root cause, but details differ. I'll comment on that issue separately.

**Comment by eemeli** [comment] 2024-10-05 14:31
Closing, as there's nothing actionable here and the current behaviour is intentional.

**Closed by eemeli** 2024-10-05 14:31 UTC
Labels: bug
