### ISSUE TITLE
Linebreaks in block fold field is not preserved

### ISSUE THREAD

**Issue by saravmajestic** [eemeli/yaml#586] opened 2024-10-21 02:07 UTC
**Describe the bug**
In my yaml file, i have block fold field `description` with a line break as in below code
```
version: 2
tables:
  - name: customers

    description: >
      This table has basic information about a customer. 
      As well as some derived facts based on a customer's orders
```
When I parse the contents as document and save it to a file, the line breaks are not preserved
```
const yaml = require("yaml");
const fs = require("fs");
const path = require("path");

const fileContents = fs.readFileSync(
  path.resolve(__dirname, "test.yml"),
  "utf8",
);

const parsedDoc = yaml.parseDocument(fileContents, {});
fs.writeFileSync(
  path.resolve(__dirname, "test1.yml"),
  yaml.stringify(parsedDoc, {}),
);
```

Ouput:
```
version: 2
tables:
  - name: customers

    description: >
      This table has basic information about a customer.  As well as some
      derived facts based on a customer's orders

```

Is it possible to restore the line breaks when saving the file?

**To Reproduce**
Mentioned above

**Expected behaviour**
Line breaks in block fold should be preserved

**Versions (please complete the following information):**

- Environment: node 20
- `yaml`: 2.6.0

**Additional context**

**Comment by eemeli** [comment] 2024-10-21 06:11
Closing as a duplicate of #572, see answer there.

**Closed by eemeli** 2024-10-21 06:11 UTC
Labels: bug
