### ISSUE TITLE
no apparent way to turn off folding for long flow mappings

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [eemeli/yaml#446] opened 2023-03-01 19:12 UTC
**Describe the bug**
I want to have a list of mappings, each one on it's own line.
the library puts long ones on multiple lines and there appears to be no way to control this.

**To Reproduce**
```js
const yaml = require("yaml")

const doc = new yaml.Document({
    foo: []
});

let node1 = doc.createNode({a:1,b:2,c:3})
let node2 = doc.createNode({d:1,e:2,f:3,g:4,h:8,i:9,j:10,k:11,l:12,m:13})

node1.flow = node2.flow = true

doc.addIn(["foo"], node1)
doc.addIn(["foo"], node2)

console.log(doc.toString());
```
observe output:
```
$ node yaml-bug.js
foo:
  - { a: 1, b: 2, c: 3 }
  - {
      d: 1,
      e: 2,
      f: 3,
      g: 4,
      h: 8,
      i: 9,
      j: 10,
      k: 11,
      l: 12,
      m: 13
    }

```
**Expected behaviour**
i don't expect this to be the *default* but there should be a way to do it
```
$ node yaml-bug.js
foo:
  - { a: 1, b: 2, c: 3 }
  - { d: 1, e: 2, f: 3, g: 4, h: 8, i: 9, j: 10, k: 11, l: 12, m: 13 }
```

**Versions**
- Node: 19.6.0
- yaml: 2.2.1

**Comment by eemeli** [comment] 2023-03-01 20:07
It's pretty ugly, but setting this value will get you the results you're looking for:

```js
import { YAMLMap } from 'yaml'

Object.getPrototypeOf(YAMLMap).maxFlowStringSingleLineLength = 2000 // or any other large number
```

As no-one before now has asked for this, I'm going to hold off on making this more ergonomic until there's a bit more interest. In other words, if this is functionality that you'd use if it was more easily available, please add a comment on this issue.

**Comment by SIGSTACKFAULT** [comment] 2023-03-02 02:24
that works for now!

when this gets fixed properly i'll use the proper solution :3

**Comment by eemeli** [comment] 2023-05-23 11:56
I just realised that this is a duplicate of #421.

**Closed by eemeli** 2023-05-23 11:56 UTC
Labels: enhancement
