### ISSUE TITLE
Missing indentation before empty lines in Literal Block Scalar Style

### ISSUE THREAD

**Issue by flekmatik** [eemeli/yaml#266] opened 2021-05-03 09:42 UTC
**Describe the bug**
When using YAML.stringify there is no indentation for empty lines when using Literal Block Scalar Style. This is breaking YAML specification.

**To Reproduce**
```
const YAML = require('yaml');
const fs = require('fs');

const example = {
    textWithEmptyLines: 'line before two empty lines\n\n\nline after two empty lines'
};
YAML.scalarOptions.str.fold.lineWidth = 0;
fs.writeFileSync('result.yaml', YAML.stringify(example));
```
**Actual Behaviour**
```
textWithEmptyLines: |-
..line before two empty lines


..line after two empty lines
```

**Expected behaviour**
```
textWithEmptyLines: |-
..line before two empty lines
..
..
..line after two empty lines
```

**Versions**

- Environment: Chrome 90.0
- `yaml`: 1.10.2, 2.0.0-5

**Additional context**
YAML spec:
![image](https://user-images.githubusercontent.com/4591928/116861879-283f0f00-ac04-11eb-828e-2866cbe24429.png)

**Comment by eemeli** [comment] 2021-05-03 11:09
This is working as intended, and does not break the spec. Empty lines in a block literal with indentation up to the expected minimum (two in the example) are caught by the `l-empty(n,block-in)*` part of the `l-nb-literal-text(n)` construction, specifically its `s-indent(<n)` part. Therefore it's perfectly valid to output an empty line as an empty line, i.e. without those spaces.

Is there a different YAML library with which this is causing you issues?

**Comment by vekonyz** [comment] 2021-05-03 11:35
Hello Eemeli,

the issue is the following: block will be terminated when less indented:
![image](https://user-images.githubusercontent.com/38154802/116871266-4c0a5100-ac14-11eb-925d-39915ac2e301.png)

**Comment by eemeli** [comment] 2021-05-03 11:46
The text there is a bit imprecise, as it really should say:
> A block style construct is terminated when encountering a line **with content** which is less indented than the construct.

If you look at examples 6.6, 6.7, or 8.10-8.13, you'll see unindented empty lines not terminating the current block construct.

**Comment by eemeli** [comment] 2021-05-06 16:25
Closing, as the current behaviour is as intended.

**Closed by eemeli** 2021-05-06 16:25 UTC
Labels: bug
