### ISSUE TITLE
`YAML.parse()` throws `YAMLSemanticError` when parse OpenAPI-Specification examples

### ISSUE THREAD

**Issue by arx-8** [eemeli/yaml#108] opened 2019-05-02 04:26 UTC
Thank you for creating an awesome package!

I got an error.
So, Can you fix this problem?

## Overview

`YAML.parse()` throws `YAMLSemanticError` when parse OpenAPI-Specification examples

## Reproducible example code

[error-reproduction.zip](https://github.com/eemeli/yaml/files/3136725/error-reproduction.zip)

## Reporter's environment

-   OS : Windows 7
-   node : v11.12.0
-   npm : 6.7.0
-   yaml : 1.5.0
-   js-yaml : 3.13.1 (For comparison)

## Issue

`YAML.parse()` throws `YAMLSemanticError`.

## Expected result

-   `YAML.parse()` throws no error.
-   `YAML.parse()` returns parsed Object.

## Supplement

Other OpenAPI-Specification examples are working.
But, Only [api-with-examples.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml) is not working...

Thank you and best regards,

**Comment by eemeli** [comment] 2019-05-02 11:07
This is not a bug with `yaml`, but with the input file. The closing curly brace `}` on [line 43](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/api-with-examples.yaml#L43) is indented by 17 spaces, but its opening brace `{` is on a line that has 18 spaces of indentation. The YAML spec requires that content within indented flow collections is indented by at least the same level. Admittedly `js-yaml` does not complain about this, but that's a mismatch between their implementation and the spec.

**Closed by eemeli** 2019-05-02 11:07 UTC

**Comment by arx-8** [comment] 2019-05-03 02:21
Thank you very much for your explanations!
I understand it.

**Comment by arx-8** [comment] 2019-05-03 02:22
@eemeli 
Thank you very much for your explanations!
I understand it.
