### ISSUE TITLE
Log the content when unsupported token error throws on composer.compose()

### ISSUE THREAD

**Issue by msivasubramaniaan** [eemeli/yaml#367] opened 2022-03-10 06:19 UTC
**Is your feature request related to a problem? Please describe.**
As we need to fix the https://github.com/redhat-developer/yaml-language-server/issues/654 issue on our side, but unable to get the content what causes this error.

**Describe the solution you'd like**
It would be great if you log the content on your side which cause this error.

**Comment by eemeli** [comment] 2022-03-11 08:19
Would you have some example of the input that's causing this issue? The tracking and logging for this should already be in place.

**Comment by eemeli** [comment] 2022-03-21 11:06
The upstream error is being thrown here: https://github.com/eemeli/yaml/blob/8f38c6aed80d649a7652c47a1d73d6cc48fb7d45/src/compose/compose-node.ts#L61-L63

It's probably caused by invalid input YAML, but it really shouldn't throw even then. If you have access to the console logs from around the error, that could reveal a bit more information?

I'll stop the error from throwing, but I would be really rather interested in getting a sample input that's causing this, as I can't even figure out how to test this.

**Comment by eemeli** [comment] 2022-04-06 09:18
Closing as presumable resolved.

**Closed by eemeli** 2022-04-06 09:18 UTC
Labels: enhancement
