### ISSUE TITLE
Latest update 2 days ago broke the typings

### ISSUE THREAD

**Issue by ffMathy** [eemeli/yaml#155] opened 2020-04-20 11:15 UTC
See my comment here: https://github.com/eemeli/yaml/commit/21dbf64d5aa7152bdd452f65f455307c1fb0b24a#r38612146

**Comment by ffMathy** [comment] 2020-04-20 11:16
Error:

> node_modules/yaml/index.d.ts:245:3 - error TS2416: Property 'toJSON' in type 'Document' is not assignable to the same property in base type 'Collection'.
>   Type '(arg?: string | undefined, onAnchor?: ((value: any, count: number) => void) | undefined) => any' is not assignable to type '(arg?: any, ctx?: NodeToJsonContext | undefined) => any'.
>     Types of parameters 'onAnchor' and 'ctx' are incompatible.
>       Type 'NodeToJsonContext | undefined' is not assignable to type '((value: any, count: number) => void) | undefined'.
>         Type 'NodeToJsonContext' is not assignable to type '(value: any, count: number) => void'.
>           Type 'NodeToJsonContext' provides no match for the signature '(value: any, count: number): void'.

**Comment by eemeli** [comment] 2020-04-20 17:22
This is a duplicate of #154, which was fixed by the 1.9.2 patch release earlier today.

**Closed by eemeli** 2020-04-20 17:22 UTC
