### ISSUE TITLE
Seemingly not all files published? 

### ISSUE THREAD

**Issue by Haroenv** [eemeli/yaml#526] opened 2024-03-01 10:57 UTC
**Describe the bug**

import of a file that doesn't exist (I don' see ../doc/directives' relative to composer)

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '../doc/directives.js'
Require stack:
- /myfolder/node_modules/patch-package/node_modules/yaml/dist/compose/composer.js
- /myfolder/node_modules/patch-package/node_modules/yaml/dist/index.js
- /myfolder/node_modules/patch-package/dist/getPackageResolution.js
- /myfolder/node_modules/patch-package/dist/makePatch.js
- /myfolder/node_modules/patch-package/dist/applyPatches.js
- /myfolder/node_modules/patch-package/dist/index.js
- /myfolder/node_modules/patch-package/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/myfolder/node_modules/patch-package/node_modules/yaml/dist/compose/composer.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/myfolder/node_modules/patch-package/node_modules/yaml/dist/compose/composer.js',
    '/myfolder/node_modules/patch-package/node_modules/yaml/dist/index.js',
    '/myfolder/node_modules/patch-package/dist/getPackageResolution.js',
    '/myfolder/node_modules/patch-package/dist/makePatch.js',
    '/myfolder/node_modules/patch-package/dist/applyPatches.js',
    '/myfolder/node_modules/patch-package/dist/index.js',
    '/myfolder/node_modules/patch-package/index.js'
  ]
}

Node.js v20.10.0
✨  Done in 0.46s.
```

**To Reproduce**

I haven't yet tried to reproduce it myself, as I don't know where it's used, but I used patch-package 8.0.0, which uses yaml 2.4.0

**Expected behaviour**

No error / all files exist

**Versions (please complete the following information):**

- Environment: Node 20.10.0
- `yaml`: 2.4.0

**Additional context**

Using yaml through patch-package

**Comment by Haroenv** [comment] 2024-03-01 10:59
<img width="168" alt="Screenshot 2024-03-01 at 11 58 26" src="https://github.com/eemeli/yaml/assets/6270048/32794fb8-fcde-461b-86bf-38d540403d64">

Still not too sure what's going on as this is in my local node_modules, but actually on npm (the website) those files _do_ seem to exist

<img width="245" alt="Screenshot 2024-03-01 at 11 59 07" src="https://github.com/eemeli/yaml/assets/6270048/50040ad9-92c7-4e92-b289-68d1c45f7caf">

**Comment by eemeli** [comment] 2024-03-01 11:55
> Using yaml through patch-package

This is the source of your problems; this is a dupe of #384.

You are using a tool that is using broken heuristics to mangle your `node_modules` contents, and you probably shouldn't.

**Comment by eemeli** [comment] 2024-03-01 11:57
Ah, sorry, it could be that it's not `patch-package` but some other tool that's mangling your `node_modules`.

**Comment by Haroenv** [comment] 2024-03-01 12:59
Hm yes it's probably another tool that removes this folder. Not sure what it is. I'll work around it for now by using a lower version, but keep this in account when I do _need_ to update.

Thanks!

**Closed** 2024-03-01 13:02 UTC
Labels: bug

**Comment by Haroenv** [comment] 2024-03-01 13:05
I found it, in the end it's also the default `.yarnclean` that removes the folder. Not sure if that can be modified, but at least I know the parts to tweak when needed.
